# Generated by Django 3.0.6 on 2020-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='timestamp',
        ),
    ]
